name: Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew installDist
      - name: Upload distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-dist
          path: build/install/thoughtsntea-bot
#
#  build-and-deploy:
#    needs: build-gradle
#    if: github.ref == 'refs/heads/master'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Download distribution artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: gradle-dist
#          path: build/install/thoughtsntea-bot
#
#      - name: Build Docker image
#        run: |
#          docker build -t thoughtsntea-bot .
#
#      - name: Save Docker image as artifact
#        run: |
#          docker save thoughtsntea-bot -o /tmp/thoughtsntea-bot.tar
#
#      - name: Upload Docker image artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: docker-image
#          path: /tmp/thoughtsntea-bot.tar
#
#      - name: Transfer Docker image to server
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_KEY }}
#          source: "/tmp/thoughtsntea-bot.tar"
#          target: "/tmp/thoughtsntea-bot.tar"
#
#      - name: Deploy on Hetzner Server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_KEY }}
#          script: |
#            docker load -i /tmp/thoughtsntea-bot.tar
#            docker stop thoughtsntea-bot || true
#            docker rm thoughtsntea-bot || true
#            docker run -d --name thoughtsntea-bot thoughtsntea-bot
