name: Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 23

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew installDist

      - name: Upload distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-dist
          path: build/install/thoughtsntea-bot

      # Docker steps that only run on master branch
      - name: 'Get version from VERSION file'
        if: github.ref == 'refs/heads/master'
        id: get-version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: 'Login to GitHub Container Registry'
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        if: github.ref == 'refs/heads/master'
        run: |
          docker build . --tag ghcr.io/thoughtsandtea/store:${{ steps.get-version.outputs.VERSION }}
          docker push ghcr.io/thoughtsandtea/store:${{ steps.get-version.outputs.VERSION }}
